### PR TITLE
Attempting to fix measurewise-q-schema where the time signature is not properly displayed.

### PR DESCRIPTION
**Pull request by nivlekp**
This pull request is attempting to fix a potential bug where the time signature is not properly displayed.

Essentially what we want to do is to display the time signature if it is different from the previous bar's.
I have modified the doctest, so that it is more consistent with the old documentation [http://abjad.mbrsi.org/api/abjadext/nauert/Quantizer.html#abjadext.nauert.Quantizer.Quantizer](http://abjad.mbrsi.org/api/abjadext/nauert/Quantizer.html#abjadext.nauert.Quantizer.Quantizer)

Although all checks have failed on Travis CI, all pytests passed on my local machine.

### CODE REVIEW

**Comment by trevorbaca** [comment]
Hi @nivlekp (also hi @josiah-wolf-oberholtzer )! I've cloned the most recent version of Nauert, and I'm currently working to bring everything up to date with the Abjad mainline (which will become the Abjad 3.2 release in a bit). I don't know if I'll be able to make everything work. But I'll check everything in when I'm done, and maybe you can check out my changes and see if we can bring Nauert up to date with Abjad 3.2.

**Comment by trevorbaca** [comment]
This PR will be possible after #7

**Comment by trevorbaca** [comment]
All Nauert tests now pass for Abjad 3.2.

**Comment by nivlekp** [comment]
Hi @trevorbaca, it seems like you have already brought everything up-to-date with Abjad 3.2, so I am assuming there's nothing more to do for now?

Thank you very much for merging the pull request!

**Comment by trevorbaca** [comment]
Hi @nivlekp, yes everything is now up to date, and your PR merged in great! Thanks for the fix!

**Pull request merged**
